# ================================================================
# Environment Sync Script
# ================================================================
# This script ensures JWT_SECRET is synchronized between main app
# and socket server to prevent authentication failures.
#
# Usage: .\sync-env.ps1
# ================================================================

Write-Host "Environment Sync Script" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local exists
if (!(Test-Path ".env.local")) {
    Write-Host "[ERROR] .env.local not found" -ForegroundColor Red
    Write-Host "        Please create .env.local from .env.template first" -ForegroundColor Yellow
    exit 1
}

# Extract JWT_SECRET from main .env.local
$jwtSecret = Get-Content ".env.local" | Where-Object { $_ -match '^JWT_SECRET=' } | ForEach-Object { $_ -replace '^JWT_SECRET=', '' }

if ([string]::IsNullOrWhiteSpace($jwtSecret)) {
    Write-Host "[ERROR] JWT_SECRET not found in .env.local" -ForegroundColor Red
    Write-Host "        Please set JWT_SECRET in .env.local" -ForegroundColor Yellow
    exit 1
}

Write-Host "[OK] Found JWT_SECRET in main .env.local" -ForegroundColor Green
Write-Host "     Length: $($jwtSecret.Length) characters" -ForegroundColor Gray

# Check security
if ($jwtSecret.Length -lt 32) {
    Write-Host "[WARNING] JWT_SECRET is less than 32 characters" -ForegroundColor Yellow
    Write-Host "          For security, use at least 32 characters" -ForegroundColor Yellow
}

# Create socket-server directory if it doesn't exist
if (!(Test-Path "socket-server")) {
    Write-Host "[INFO] Creating socket-server directory..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path "socket-server" -Force | Out-Null
}

# Check if socket-server .env exists
$socketEnvPath = "socket-server\.env"
$socketEnvExists = Test-Path $socketEnvPath

if ($socketEnvExists) {
    # Update existing file
    $content = Get-Content $socketEnvPath
    $updated = $false
    
    $newContent = $content | ForEach-Object {
        if ($_ -match '^JWT_SECRET=') {
            $updated = $true
            "JWT_SECRET=$jwtSecret"
        } else {
            $_
        }
    }
    
    if (!$updated) {
        # JWT_SECRET not found, add it
        $newContent += "JWT_SECRET=$jwtSecret"
    }
    
    Set-Content -Path $socketEnvPath -Value $newContent
    Write-Host "[OK] Updated JWT_SECRET in $socketEnvPath" -ForegroundColor Green
} else {
    # Create new file from template
    if (Test-Path "socket-server\.env.template") {
        $template = Get-Content "socket-server\.env.template"
        $newContent = $template | ForEach-Object {
            if ($_ -match '^JWT_SECRET=') {
                "JWT_SECRET=$jwtSecret"
            } else {
                $_
            }
        }
        Set-Content -Path $socketEnvPath -Value $newContent
        Write-Host "[OK] Created $socketEnvPath with JWT_SECRET" -ForegroundColor Green
    } else {
        # Create minimal .env
        $minimalEnv = @"
# Socket Server Environment Variables
# Generated by sync-env.ps1

JWT_SECRET=$jwtSecret
PORT=3001
NODE_ENV=development
CORS_ORIGIN=http://localhost:3000
"@
        Set-Content -Path $socketEnvPath -Value $minimalEnv
        Write-Host "[OK] Created $socketEnvPath with JWT_SECRET" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "[SUCCESS] Environment sync complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review socket-server\.env file" -ForegroundColor Gray
Write-Host "  2. Restart socket server if running" -ForegroundColor Gray
Write-Host "  3. Test socket authentication after restart" -ForegroundColor Gray
Write-Host ""
